unbind C-b
set-option -g prefix C-w
bind-key C-w send-prefix
bind s split-window -v
bind v split-window -h
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind > resize-pane -L 10
bind < resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10
