# Base16 Generated - kitty color config
# Scheme by Flavours
background #3b1d29
foreground #f0eaec
selection_background #f0eaec
selection_foreground #3b1d29
url_color #ccc1c5
cursor #f0eaec
cursor_text_color #3b1d29
active_border_color #a7989e
inactive_border_color #5f4650
active_tab_background #3b1d29
active_tab_foreground #f0eaec
inactive_tab_background #5f4650
inactive_tab_foreground #ccc1c5
tab_bar_background #5f4650
wayland_titlebar_color #3b1d29
macos_titlebar_color #3b1d29

# normal
color0 #3b1d29
color1 #6e798e
color2 #b95b70
color3 #717a7a
color4 #657b90
color5 #926b92
color6 #66799e
color7 #f0eaec

# bright
color8 #a7989e
color9 #538178
color10 #5f4650
color11 #836f77
color12 #ccc1c5
color13 #f2edef
color14 #bc5871
color15 #f4f0f2