# Base16 Generated - kitty color config
# Scheme by Flavours
background #442028
foreground #ffffff
selection_background #ffffff
selection_foreground #442028
url_color #dbd4d5
cursor #ffffff
cursor_text_color #442028
active_border_color #b5a7aa
inactive_border_color #6a4d53
active_tab_background #442028
active_tab_foreground #ffffff
inactive_tab_background #6a4d53
inactive_tab_foreground #dbd4d5
tab_bar_background #6a4d53
wayland_titlebar_color #442028
macos_titlebar_color #442028

# normal
color0 #442028
color1 #c84d72
color2 #e03453
color3 #a460a4
color4 #ea1e47
color5 #d0466d
color6 #e92626
color7 #ffffff

# bright
color8 #b5a7aa
color9 #cc4a6d
color10 #6a4d53
color11 #8f7a7f
color12 #dbd4d5
color13 #ffffff
color14 #c84694
color15 #ffffff