# Base16 Generated - kitty color config
# Scheme by Flavours
background #442028
foreground #ffffff
selection_background #ffffff
selection_foreground #442028
url_color #e1dcdd
cursor #ffffff
cursor_text_color #442028
active_border_color #b9adb0
inactive_border_color #6b4f55
active_tab_background #442028
active_tab_foreground #ffffff
inactive_tab_background #6b4f55
inactive_tab_foreground #e1dcdd
tab_bar_background #6b4f55
wayland_titlebar_color #442028
macos_titlebar_color #442028

# normal
color0 #442028
color1 #ec1f25
color2 #ea1e47
color3 #b15c87
color4 #c84694
color5 #e03453
color6 #a460a4
color7 #ffffff

# bright
color8 #b9adb0
color9 #ea213a
color10 #6b4f55
color11 #927e83
color12 #e1dcdd
color13 #ffffff
color14 #e92626
color15 #ffffff