ytdl-format=bestvideo[height<=?480]+worstaudio/worst
sub-file-paths=Subs
sub-auto=fuzzy
save-position-on-quit=yes
volume=60
af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5'
keep-open

[default]
[extension.gif]
cache=no
no-pause
loop-file=yes
[extension.webm]
no-pause
loop-file=yes
