[a-general]
home = "gemini://medusae.space/"
auto_redirect = true
http = 'link-handler'
search = "gemini://geminispace.info/search"

[keybindings]
bind_bottom = ":"

[auth]
[auth.certs]
"astrobotany.mozz.us" = "~/.local/share/amfora/astrobotany-cert.pem"

[auth.keys]
"astrobotany.mozz.us" = "~/.local/share/amfora/astrobotany-key.pem"

[[mediatype-handlers]]
cmd = ['feh']
types = ["image"]
no_prompt = true

# Start flavours
# Base16 Darcula - amfora color config
# jetbrains

[theme]
bg = "#2b2b2b"
fg = "#a9b7c6"

bottombar_label = "#cc7832"
bottombar_text = "#a9b7c6"
bottombar_bg = "#323232"

tab_num = "#323232"
tab_divider = "#a4a3a3"

amfora_link = "#6a8759"
foreign_link = "#606366"
link_number = "#606366"

btn_bg = "#323232"
btn_text = "#a9b7c6"

input_modal_bg = "#323232"
input_modal_text = "#a9b7c6"
input_modal_field_bg = "#2b2b2b"
input_modal_field_text = "#a9b7c6"
info_modal_bg = "#323232"
info_modal_text = "#a9b7c6"
error_modal_bg = "#323232"
error_modal_text = "#808080"
yesno_modal_bg = "#323232"
yesno_modal_text = "#a9b7c6"
tofu_modal_bg = "#323232"
tofu_modal_text = "#a9b7c6"
subscription_modal_bg = "#323232"
subscription_modal_text = "#a9b7c6"

hdg_1 = "#689757"
hdg_2 = "#bbb529"
hdg_3 = "#9876aa"
regular_text = "#a9b7c6"
preformatted_text = "#629755"
list_text = "#a9b7c6"
# End Flavours
