[a-general]
home = "gemini://medusae.space/"
auto_redirect = true
http = 'link-handler'
search = "gemini://geminispace.info/search"

[keybindings]
bind_bottom = ":"

[auth]
[auth.certs]
"astrobotany.mozz.us" = "~/.local/share/amfora/astrobotany-cert.pem"

[auth.keys]
"astrobotany.mozz.us" = "~/.local/share/amfora/astrobotany-key.pem"

[[mediatype-handlers]]
cmd = ['feh']
types = ["image"]
no_prompt = true

# Start flavours
# Base16 Generated - amfora color config
# Flavours

[theme]
bg = "#262626"
fg = "#cbcbcb"

bottombar_label = "#787878"
bottombar_text = "#cbcbcb"
bottombar_bg = "#474747"

tab_num = "#686868"
tab_divider = "#aaaaaa"

amfora_link = "#a162a1"
foreign_link = "#898989"
link_number = "#898989"

btn_bg = "#474747"
btn_text = "#cbcbcb"

input_modal_bg = "#474747"
input_modal_text = "#cbcbcb"
input_modal_field_bg = "#262626"
input_modal_field_text = "#cbcbcb"
info_modal_bg = "#474747"
info_modal_text = "#cbcbcb"
error_modal_bg = "#474747"
error_modal_text = "#787878"
yesno_modal_bg = "#474747"
yesno_modal_text = "#cbcbcb"
tofu_modal_bg = "#474747"
tofu_modal_text = "#cbcbcb"
subscription_modal_bg = "#474747"
subscription_modal_text = "#cbcbcb"

hdg_1 = "#4e854e"
hdg_2 = "#9c6e4f"
hdg_3 = "#787878"
regular_text = "#cbcbcb"
preformatted_text = "#787878"
list_text = "#cbcbcb"
# End Flavours
