[a-general]
home = "gemini://medusae.space/"
auto_redirect = true
http = 'link-handler'
search = "gemini://geminispace.info/search"

[keybindings]
bind_bottom = ":"

[auth]
[auth.certs]
"astrobotany.mozz.us" = "~/.local/share/amfora/astrobotany-cert.pem"

[auth.keys]
"astrobotany.mozz.us" = "~/.local/share/amfora/astrobotany-key.pem"

[[mediatype-handlers]]
cmd = ['feh']
types = ["image"]
no_prompt = true

# Start flavours
# Base16 Generated - amfora color config
# Flavours

[theme]
bg = "#382119"
fg = "#c7bcae"

bottombar_label = "#ba6011"
bottombar_text = "#c7bcae"
bottombar_bg = "#554037"

tab_num = "#715f55"
tab_divider = "#ab9d90"

amfora_link = "#b49303"
foreign_link = "#8e7e72"
link_number = "#8e7e72"

btn_bg = "#554037"
btn_text = "#c7bcae"

input_modal_bg = "#554037"
input_modal_text = "#c7bcae"
input_modal_field_bg = "#382119"
input_modal_field_text = "#c7bcae"
info_modal_bg = "#554037"
info_modal_text = "#c7bcae"
error_modal_bg = "#554037"
error_modal_text = "#c35914"
yesno_modal_bg = "#554037"
yesno_modal_text = "#c7bcae"
tofu_modal_bg = "#554037"
tofu_modal_text = "#c7bcae"
subscription_modal_bg = "#554037"
subscription_modal_text = "#c7bcae"

hdg_1 = "#a46c2c"
hdg_2 = "#ad680b"
hdg_3 = "#ae6641"
regular_text = "#c7bcae"
preformatted_text = "#c28623"
list_text = "#c7bcae"
# End Flavours
