#!/bin/bash
# Update alacritty config to apply Xresources color scheme

# Target file
target_file="$HOME/.config/xob/styles.cfg"

cp $target_file.in $target_file.tmp

xrdb ~/.Xresources

for i in {0..15}
do
    v=`xrdb -query | awk '/*.color'"$i":'/ { print substr($2,2) }'`
    #echo $v
    eval "sed -i 's/%cl${i}%/#${v}/g' $target_file.tmp";
done

foreground=`xrdb -query | awk '/*.foreground/ { print substr($2,2) }'`
background=`xrdb -query | awk '/*.background/ { print substr($2,2) }'`
sed -i "s/%clfg%/#${foreground}/g" $target_file.tmp
sed -i "s/%clbg%/#${background}/g" $target_file.tmp

rm $target_file
mv $target_file.tmp $target_file
