$font = Monospace

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    noise = 0.2
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

# Start flavours
    outer_color = rgba(b5a7aaee) rgba(8f7a7fee) 45deg
    check_color = rgba(8f7a7fee) rgba(b5a7aaee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
# End flavours

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text =
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

image {
  monitor =
  path = ~/.face.png
  size = 150
  rounding = -1
  position = 0, 100
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}
