source = ./monitors.conf
source = ./auto-start.conf
source = ./animations.conf
source = ./smart-gaps.conf
source = ./theme.conf
source = ./keybindings.conf
source = ./rules.conf

env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,10
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,10

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = false
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = compose:ralt
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

debug {
  disable_logs = false
}

gesture = 3, horizontal, workspace
