windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class vivaldi-stable
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class krita
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:title Picture in picture

# Picture-in-Picture
windowrule {
    name = hyde_picture_in_picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    tag = +picture-in-picture
    tag = +hyde_picture_in_picture
    float = true
    keep_aspect_ratio = true
    move = (monitor_w*0.73) (monitor_h*0.72)
    size = (monitor_w*0.25) (monitor_h*0.25)
    pin = true
}
