shell = "bash -c '{}'"

[[item]]
file = "~/.mozilla/firefox/d8a6lpyr.default-release/chrome/userChrome.css"
template = "firefox"
start= "/* Start Flavours */"
end = "/* End flavours */"

[[item]]
file = "~/.config/tridactyl/themes/base16.css"
template = "tridactyl"
subtemplate = "default-alt"
rewrite = true

[[item]]
file = "~/.doom.d/themes/base16-theme.el"
template = "emacs"
rewrite = true

[[item]]
file = "~/.xmonad/lib/MyColors.hs"
template = "xmonad"
rewrite = true

[[item]]
file = "~/.config/polybar/config"
template = "polybar"

[[item]]
file = "~/.config/alacritty/alacritty.yml"
template = "alacritty"

[[item]]
file = "~/.Xresources"
template = "xresources"
start= "! Start flavours"
end = "! End flavours"
hook = "xrdb ~/.Xresources"

[[item]]
file = "~/.config/zathura/zathurarc"
template = "zathura"
subtemplate = "recolor"

[[item]]
file = "~/.config/nvim/colors/base16.vim"
template = "vim"
rewrite = true

[[item]]
file = "~/.config/qutebrowser/config.py"
template = "qutebrowser"

[[item]]
file = "~/.config/amfora/config.toml"
template = "amfora"

[[item]]
file = "~/.config/xob/styles.cfg"
template = "xob"

[[item]]
file = "~/.config/xob/styles.cfg"
template = "xob"
start= "## Start flavours"
end = "## End flavours"

[[item]]
file = "~/.browser/style.css"
template = "startpage"
start= "/* Start flavours */"
end = "/* End flavours */"

[[item]]
file = "~/.themes/FlatColor/colors2"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
rewrite = true

[[item]]
file = "~/.themes/FlatColor/colors3"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = true
