shell = "bash -c '{}'"

[[item]]
file = "~/.Xresources"
template = "xresources"
start= "! Start flavours"
end = "! End flavours"
hook = "xrdb ~/.Xresources"

[[item]]
file = "~/.config/zathura/zathurarc"
template = "zathura"
subtemplate = "recolor"

[[item]]
file = "~/.config/nvim/colors/base16.vim"
template = "vim"
rewrite = true

[[item]]
file = "~/.config/amfora/config.toml"
template = "amfora"

[[item]]
file = "~/.themes/FlatColor/colors2"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
rewrite = true

[[item]]
file = "~/.themes/FlatColor/colors3"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = true

[[item]]
file = "~/.git/dwm/config.def.h"
template = "dwm"
start = "// Start flavours"
end = "// End flavours"
