############# Shadows ###########
shadow = false
# shadow-radius = 7;
# shadow-opacity = .75
# shadow-offset-x = -7;
# shadow-offset-y = -7;
# shadow-red = 0
# shadow-green = 0
# shadow-blue = 0
# shadow-exclude-reg = "" 
# xinerama-shadow-crop = false

########### Fading ##############
fading = false
# fade-in-step = 0.028
# fade-out-step = 0.03
# fade-delta = 10

### Transparency / Opacity ######
inactive-opacity = 1
frame-opacity = 1.0
menu-opacity = 1.0
inactive-opacity-override = true
active-opacity = 1.0
# inactive-dim = 0.0
focus-exclude = [ "class_g = 'Cairo-clock'" ];
# inactive-dim-fixed = 1.0

##### Background-Blurring #######
# blur-method = 
# blur-size = 12
# blur-deviation = false
# blur-background = false
# blur-background-frame = false
# blur-background-fixed = false
# blur-kern = ''
# blur-background-exclude = []

####### General Settings ########
# daemon = false
# backend = 'glx'
vsync = true
# dbus = false
# mark-wmwin-focused = false
# mark-ovredir-focused = false
# detect-rounded-corners = false
# detect-client-opacity = false
refresh-rate = 0
# sw-opti = 
# use-ewmh-active-win = false
unredir-if-possible = true
# unredir-if-possible-delay = 0
# unredir-if-possible-exclude = []
# detect-transient = false
# detect-transient = true
# detect-client-leader = true
# resize-damage = 1
# invert-color-include = []
# glx-no-stencil = false
# glx-no-rebind-pixmap = false
# no-use-damage = false
use-damage = true
# xrender-sync-fence = false
# glx-fshader-win = ''
# force-win-blend = false
# no-ewmh-fullscreen = false
# max-brightness = 1.0
# transparent-clipping = false
log-level = "warn";
# log-file = '/path/to/your/log/file'
# show-all-xerrors = false
# write-pid-path = '/path/to/your/log/file'
wintypes:
{
  dock = { shadow = false; }
  dnd = { shadow = false; }
};
