shell = "bash -c '{}'"

[[item]]
file = "~/.Xresources"
template = "xresources"
start= "! Start flavours"
end = "! End flavours"
hook = "xrdb ~/.Xresources"

[[item]]
file = "~/.config/ghostty/themes/generated"
template = "ghostty"
start = "# Start flavours"
end = "# End flavours"

[[item]]
file = "~/.config/rofi/theme.rasi"
template="rofi"
subtemplate="colors"
start = "// Start flavours"
end = "// End flavours"
